# Generated by Django 5.1 on 2024-09-07 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill_builder', '0002_languageword'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicfather',
            name='topic_father_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='topicfather',
            name='topic_father_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='topicfather',
            name='topic_father_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='topicfather',
            name='topic_father_pt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
