# Generated by Django 5.1 on 2024-09-08 20:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill_builder', '0003_topicfather_topic_father_de_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TableForm03',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title_Name', models.CharField(max_length=50)),
                ('Language', models.CharField(max_length=50)),
                ('Topic_Father', models.CharField(max_length=50)),
                ('Topic_Son', models.TextField()),
                ('Description', models.CharField(max_length=255)),
                ('Level_CEFR', models.CharField(max_length=2)),
                ('number_setence', models.IntegerField()),
                ('rating', models.FloatField(blank=True, null=True)),
                ('number_votes', models.IntegerField(default=0)),
                ('id_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SpanishSentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_sentence', models.FloatField(blank=True, null=True)),
                ('number_votes_sentence', models.IntegerField(default=0)),
                ('Sentence', models.CharField(max_length=100)),
                ('id_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spanish_sentences', to='skill_builder.tableform03')),
            ],
        ),
        migrations.CreateModel(
            name='EnglishSentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_sentence', models.FloatField(blank=True, null=True)),
                ('number_votes_sentence', models.IntegerField(default=0)),
                ('Sentence', models.CharField(max_length=100)),
                ('id_FK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='english_sentences', to='skill_builder.tableform03')),
            ],
        ),
    ]
