# Generated by Django 5.1 on 2024-11-30 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill_builder', '0004_tableform03_spanishsentence_englishsentence'),
    ]

    operations = [
        migrations.CreateModel(
            name='TablaMaestra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb_tense', models.CharField(max_length=50, verbose_name='Tiempo Verbal')),
                ('grammatical_category', models.CharField(max_length=50, verbose_name='Categoría Gramatical')),
                ('related_subtopic', models.CharField(max_length=50, verbose_name='Submateria Relacionada')),
                ('order', models.IntegerField(verbose_name='Orden')),
            ],
        ),
    ]
