# Generated by Django 5.1 on 2024-12-01 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill_builder', '0005_tablamaestra'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentPerformance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('oracion_generada', models.TextField(blank=True, null=True, verbose_name='Oración Generada')),
                ('score', models.IntegerField(blank=True, null=True, verbose_name='Puntaje')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Nota')),
                ('key_areas', models.TextField(blank=True, null=True, verbose_name='Áreas Clave')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('id_fk_tabla_maestra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_performances', to='skill_builder.tablamaestra', verbose_name='Referencia a TablaMaestra')),
                ('id_fk_topic_father', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_performances', to='skill_builder.topicfather', verbose_name='Referencia a TopicFather')),
                ('id_fk_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_performances', to=settings.AUTH_USER_MODEL, verbose_name='Referencia a Usuario')),
            ],
        ),
    ]
